"""rename input_map_id input_map_product_id

Revision ID: 1a6a95202069
Revises: 3c88fd09fbae
Create Date: 2020-05-12 15:10:02.013564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6a95202069'
down_revision = '3c88fd09fbae'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beams', 'input_map_id', new_column_name='input_map_product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beams', 'input_map_product_id', new_column_name='input_map_id')
    # ### end Alembic commands ###
