"""empty message

Revision ID: 3c5d60d0c0d8
Revises: bebcdfcb5077
Create Date: 2020-05-05 11:48:31.221421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5d60d0c0d8'
down_revision = 'bebcdfcb5077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('contact', sa.Text(), nullable=True))
    op.add_column('maps', sa.Column('date_produced', sa.Date(), nullable=True))
    op.add_column('maps', sa.Column('date_updated', sa.Date(), nullable=True))
    op.add_column('maps', sa.Column('posted_by', sa.Text(), nullable=True))
    op.add_column('maps', sa.Column('updated_by', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'updated_by')
    op.drop_column('maps', 'posted_by')
    op.drop_column('maps', 'date_updated')
    op.drop_column('maps', 'date_produced')
    op.drop_column('maps', 'contact')
    # ### end Alembic commands ###
