"""rename simulation_file_path_id path_id

Revision ID: 3c88fd09fbae
Revises: b6be74fe2785
Create Date: 2020-05-12 14:55:57.938656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c88fd09fbae'
down_revision = 'b6be74fe2785'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulation_file_paths', 'simulation_file_path_id', new_column_name='path_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulation_file_paths', 'path_id', new_column_name='simulation_file_path_id')
    # ### end Alembic commands ###
