"""rename date_posted date_produced

Revision ID: 4796e7f9c766
Revises: 7f50d622bc34
Create Date: 2020-05-12 19:28:03.472291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4796e7f9c766'
down_revision = '7f50d622bc34'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulations', 'date_posted', new_column_name='date_produced')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulations', 'date_produced', new_column_name='date_produced')
    # ### end Alembic commands ###
