"""rename map_file_pah_id path_id

Revision ID: 8f76dc6db945
Revises: fa747b4e8b47
Create Date: 2020-05-12 14:41:49.723511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f76dc6db945'
down_revision = 'fa747b4e8b47'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_file_paths', 'map_file_path_id', new_column_name='path_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_file_paths', 'path_id', new_column_name='map_file_path_id')
    # ### end Alembic commands ###
