"""rename beam_id product_id

Revision ID: a7938a183f26
Revises: abc92bb44e41
Create Date: 2020-05-12 14:00:12.670351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7938a183f26'
down_revision = 'abc92bb44e41'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beams', 'beam_id', new_column_name='product_id')
    op.alter_column('beam_file_paths', 'beam_id', new_column_name='product_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beams', 'product_id', new_column_name='beam_id')
    op.alter_column('beam_file_paths', 'product_id', new_column_name='beam_id')
    # ### end Alembic commands ###
