"""rename map_id product_id

Revision ID: abc92bb44e41
Revises: 3c5d60d0c0d8
Create Date: 2020-05-12 13:40:43.177437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc92bb44e41'
down_revision = '3c5d60d0c0d8'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maps', 'map_id', new_column_name='product_id')
    op.alter_column('map_file_paths', 'map_id', new_column_name='product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maps', 'product_id', new_column_name='map_id')
    op.alter_column('map_file_paths', 'product_id', new_column_name='map_id')
    # ### end Alembic commands ###
