"""rename beam_file_path_id path_id

Revision ID: b6be74fe2785
Revises: 8f76dc6db945
Create Date: 2020-05-12 14:48:43.680805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6be74fe2785'
down_revision = '8f76dc6db945'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beam_file_paths', 'beam_file_path_id', new_column_name='path_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beam_file_paths', 'path_id', new_column_name='beam_file_path_id')
    # ### end Alembic commands ###
