"""empty message

Revision ID: bebcdfcb5077
Revises: ef4e36b7f296
Create Date: 2020-05-04 20:28:45.230781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebcdfcb5077'
down_revision = 'ef4e36b7f296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maps', 'mapper', new_column_name='produced_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maps', 'produced_by', new_column_name='mapper')
    # ### end Alembic commands ###
