"""rename input_beam_id input_beam_product_id

Revision ID: d06579a3102e
Revises: 1a6a95202069
Create Date: 2020-05-12 15:15:13.329205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06579a3102e'
down_revision = '1a6a95202069'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beams', 'input_beam_id', new_column_name='input_beam_product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beams', 'input_beam_product_id', new_column_name='input_beam_id')
    # ### end Alembic commands ###
