"""inherit CommonFields in Simulation

Revision ID: d164761c73d2
Revises: 4796e7f9c766
Create Date: 2020-05-12 19:35:17.335887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd164761c73d2'
down_revision = '4796e7f9c766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('contact', sa.Text(), nullable=True))
    op.add_column('simulations', sa.Column('date_posted', sa.Date(), nullable=True))
    op.add_column('simulations', sa.Column('date_updated', sa.Date(), nullable=True))
    op.add_column('simulations', sa.Column('posted_by', sa.Text(), nullable=True))
    op.add_column('simulations', sa.Column('updated_by', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'updated_by')
    op.drop_column('simulations', 'posted_by')
    op.drop_column('simulations', 'date_updated')
    op.drop_column('simulations', 'date_posted')
    op.drop_column('simulations', 'contact')
    # ### end Alembic commands ###
