"""rename simulation_id product_id

Revision ID: fa747b4e8b47
Revises: a7938a183f26
Create Date: 2020-05-12 14:08:30.103907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa747b4e8b47'
down_revision = 'a7938a183f26'
branch_labels = None
depends_on = None

# Alembic document alter_column()
# https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulations', 'simulation_id', new_column_name='product_id')
    op.alter_column('simulation_file_paths', 'simulation_id', new_column_name='product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulations', 'product_id', new_column_name='simulation_id')
    op.alter_column('simulation_file_paths', 'product_id', new_column_name='simulation_id')
    # ### end Alembic commands ###
