"""GraphQL queries as strings

"""

from .fragments import (  # noqa: F401
    FRAGMENT_PRODUCT,
    FRAGMENT_PRODUCT_SHALLOW,
    FRAGMENT_PRODUCT_CONNECTION,
    FRAGMENT_PRODUCT_CONNECTION_SHALLOW,
    FRAGMENT_PRODUCT_RELATION_TYPE,
    FRAGMENT_PRODUCT_RELATION_TYPE_CONNECTION,
    FRAGMENT_PRODUCT_RELATION,
    FRAGMENT_PRODUCT_RELATION_CONNECTION,
    FRAGMENT_PRODUCT_TYPE,
    FRAGMENT_PRODUCT_TYPE_CONNECTION,
)

from .mutations import (  # noqa: F401
    MUTATION_CREATE_PRODUCT,
    MUTATION_DELETE_PRODUCT,
    MUTATION_UPDATE_PRODUCT,
)

from .product_relation_type import (  # noqa: F401
    MUTATION_CREATE_PRODUCT_RELATION_TYPES,
    MUTATION_UPDATE_PRODUCT_RELATION_TYPE,
    MUTATION_DELETE_PRODUCT_RELATION_TYPES,
)

from .product_relation import (  # noqa: F401
    MUTATION_CREATE_PRODUCT_RELATION,
    MUTATION_DELETE_PRODUCT_RELATION,
)

from .product_type import (  # noqa: F401
    MUTATION_CREATE_PRODUCT_TYPE,
    MUTATION_UPDATE_PRODUCT_TYPE,
    MUTATION_DELETE_PRODUCT_TYPE,
)
